### PR TITLE
Update CustomUserRepository.php

### PR DESCRIPTION
**Pull request by joshcanhelp**
Updating to null coalescing op. Using `??` would throw a notice if the array key was empty.

### CODE REVIEW

**Comment by tpenaranda** [comment]
Oh! That typo was me, thanks for fixing @joshcanhelp.

**Comment by joshcanhelp** [comment]
@tpenaranda - No problem. I reviewed the code so I should have caught it then :)

**Review by stevehobbsdev — APPROVED** [review]

**Comment by lbalmaceda** [comment]
@joshcanhelp @stevehobbsdev is this PR still valid?

**Comment by stevehobbsdev** [comment]
Revisiting this, not sure I understand the description of the work - we're saying that "using `??` would throw a notice if the array key was empty" but that's what PR code changes. Is the notice desirable? The ways it's worded makes me think not.

Also, what's a "notice" in this context? Are we talking about an interpretor warning?

**Comment by tpenaranda** [comment]
This PR is a fix for a typo for the null coalescing operator. Double pipe is used on JS, not PHP so we have a syntax error here.

Then for `'name' => $profile['name'] || ''` proper PHP syntax is `'name' => $profile['name'] ?? ''`

Why the null coalescing there? I don't know but my guess is 'name' key could not exist on $profile and we want to skip the php warning/notice.

Thanks! @stevehobbsdev @lbalmaceda

**Comment by lbalmaceda** [comment]
@tpenaranda that makes sense, thanks for taking the time to explain it. I guess if the scope is not the proper one, then yes those values could be null/empty. I'd say it doesn't hurt to add this 👍

**Pull request merged**
